spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
    async:
      request-timeout: 3600000
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB

logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml

mybatis-plus:
  configuration:
    # 懒加载(需要哪个就加载哪个，设为true一次懒加载则加载所有懒加载)
    aggressive-lazy-loading: false
    lazy-loading-enabled: true
    auto-mapping-unknown-column-behavior: warning
    # 单机时才开启一级缓存，否则会导致数据不同步
    local-cache-scope: session
    # 二级缓存，暂时还没看，开启则实体类需要实现序列化接口
    cache-enabled: false
    map-underscore-to-camel-case: true

  global-config:
    db-config:
      id-type: auto
      table-underline: true
      insert-strategy: not_null
      update-strategy: not_null
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: cn.windors.file.entity
  type-enums-package: cn.windors.file.enums
  executor-type: reuse
server:
  port: 9870